version: '3.8'
services:
  db:
    image: mariadb
    build: ./db-dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3060:3060
    volumes:
      - db:/bitnami/mariadb
      - ./init:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=3306
    stdin_open: true
    tty: true
volumes:
  db:
